from __future__ import annotations

TV_LAMBDA_RANGE: tuple[float, float] = (1e-3, 1.0)
TV_STOP_TOLERANCE: float = 0.00000005
TV_MAX_NUM_ITER: int = 50
MAP_SAMPLING: int = 3

KWEIGHT_PARAMETER_DEFAULT = 0.05

COMPUTED_MAP_RESOLUTION_LIMIT = 1.0
GEMMI_HIGH_RESOLUTION_BUFFER = 1e-6
