name: deploy

on:
  push:
    tags:        
      - '*'   

jobs:

  validate:
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.11'
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check --output-format=github .

      - name: mypy
        run: |
          pip install mypy
          pip install '.[tests]'
          mkdir .mypy_cache
          mypy --install-types --non-interactive meteor/ test/

      - name: Test with pytest
        run: |
          pip install '.[tests]'
          pytest test/

  deploy:
    name: deploy
    runs-on: [ubuntu-latest]

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install
        run: |
          git tag
          pip install -U pip
          pip install -U build twine
          python -m build
          twine check dist/*
          ls -lh dist
      - name: build and publish
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_KEY }}

      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
