name: run-examples

on:
  pull_request:
  workflow_call:
    inputs:
      job:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(vars.PYTHON_VERSIONS) }}
    
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    
    - name: Ensure notebooks complete without errors with pytest and nbmake
      run: |
        pip install '.[tests,notebooks]'
        pytest --nbmake examples/*ipynb
