name: ruff

on:
  - push

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    
    # - name: Lint with Ruff
    #   run: |
    #     pip install ruff
    #     ruff check --output-format=github .

    - name: ruff via tox
      run: python -m tox
      env:
        PLATFORM: ${{ matrix.platform }}
    
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
