name: tests

on:
  pull_request:
  schedule:
    - cron: "0 12 * * 1" # monday at noon GMT

jobs:
  build:

    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        # the platform version here only dictates the base env for Tox to run in
        python-version: ['3.11']
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        access_token: ${{ github.token }}
        
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions

    - name: Test with tox
      run: python -m tox
      env:
        PLATFORM: ${{ matrix.platform }}
        
    # - name: Test with pytest
    #   run: |
    #     pip install '.[tests]'
    #     pytest test/
    
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
